import pickle    # Importing the pickle module to read database...
import os        # importing os module to set directory...

os.chdir(r"C:\Users\saive\OneDrive\Desktop\CODING WORK\Python programs\Voice assistant(Mini project)")

with open("chatHistory.pickle","rb") as fp:         # open pickle file in fp...
    while 1:
        try:
            s = pickle.load(fp)                     # load the content to a variable...
            print(s)                                # print on the terminal..
        except:
            break
fp.close()                                          # close the pickle file...